-- #3 
WITH AVAILABILITY AS (SELECT CAR_ID 
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE 
                        OR'2022-11-30' BETWEEN START_DATE AND END_DATE)
                     
                     
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, 
        ROUND((C.DAILY_FEE*30)*(1-(P.DISCOUNT_RATE/100)),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C 
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H USING(CAR_ID)
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P USING(CAR_TYPE)
WHERE C.CAR_TYPE IN ("세단",'SUV') 
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM AVAILABILITY)
    AND P.DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000 AND FEE <2000000
ORDER BY 3 DESC, 2, 1 DESC;