SELECT
    CAR_ID,
    C.CAR_TYPE,
    FLOOR(30 * DAILY_FEE * (1 - DIS.DISCOUNT_RATE / 100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DIS ON C.CAR_TYPE = DIS.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND DIS.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
        WHERE C.CAR_ID = RH.CAR_ID
            AND RH.END_DATE >= '2022-11-01'
            AND RH.START_DATE <= '2022-11-30'
    )
HAVING
    FEE >= 500000 AND FEE < 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;
