SELECT YEAR(SALES_DATE) YEAR, 
       MONTH(SALES_DATE) MONTH, 
       GENDER, 
       COUNT(DISTINCT U.USER_ID) USERS
       
FROM USER_INFO as U
JOIN ONLINE_SALE as O
ON U.USER_ID = O.USER_ID
AND U.GENDER IS NOT NULL

GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER