SELECT YEAR(SALE.SALES_DATE) YEAR 
      ,MONTH(SALE.SALES_DATE) MONTH
      ,COUNT(DISTINCT SALE.USER_ID) PUCHASED_USERS
      ,ROUND(COUNT(DISTINCT SALE.USER_ID)/(SELECT COUNT(USER_ID) 
                                      FROM USER_INFO 
                                      WHERE YEAR(JOINED) = 2021),1) PUCHASED_RATIO
FROM USER_INFO INFO 
JOIN ONLINE_SALE SALE USING (USER_ID)
WHERE YEAR(INFO.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH