SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE MONTH(START_DATE) IN (8, 9, 10)
                 GROUP BY CAR_ID
                 HAVING COUNT(CAR_ID) >= 5)
      AND MONTH(START_DATE) IN (8, 9, 10) 
GROUP BY MONTH, CAR_ID
HAVING RECORDS >=1 
ORDER BY MONTH, CAR_ID DESC


